server:
  port: 7086

spring:
  jpa:
    show-sql: true
  datasource:
    username: db_user
    password: qwerty
    url: jdbc:postgresql://localhost:5432/simple_db
#    password: qwerty159753
#    url: jdbc:postgresql://rc1b-ntnvoyyobhhfx8pe.mdb.yandexcloud.net:6432/simple_db
  liquibase:
    change-log: classpath:liquibase/db.changelog.xml
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
#    bootstrap-servers: 10.129.0.4:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

kafka:
  autoStartup: true

client:
  message-storage-service: http://localhost:7072
  auth-service: http://localhost:8071


